import green from "@material-ui/core/colors/green";

const styles = () => ({
  PoweredBy: {
    width: " 100%",
    position: "absolute",
    bottom: "70px",
    paddingBottom: "-120px",
    color: " #ffffff",
    opacity: "0.39",
    fontSize: "16px",
    textAlign: "center",
  },
  error: {
    color: "red",
    textAlign: "center",
  },
  h1: {
    color: "#1daab1",
    textTransform: "uppercase",
    opacity: "1",
    letterSpacing: "0px",
    fontSize: "24px",
    margin: "10px 0 0 0",
    fontWeight: "500",
    marginTop: "50px",
    marginBottom: "5px",
    fontWeight: "bold",
  },
  loginPage: {
    padding: "0px",
    margin: "0px",
    letterSpacing: "0px",
    color: "#1daab1",
    opacity: "1",
    fontSize: "14px",
    textDecoration: "none",
  },
  leftContent: {
    background: "#fff",
    float: "left",
    // marginRight: "20%",
    backgroundRepeat: "no-repeat",
    opacity: "1",
    textAlign: "center",
    margin: " -10px 0 0 0",
    position: " relative",
  },
  leftImage: {
    position: "absolute",
    position: " relative",
    width: "100%",

    padding: "0px",
    margin: "70px 0 0 0",
  },
  leftImage1: {
    position: " relative",
    width: "80%",
    marginTop: "-100%",
    marginLeft: "-40px",
    padding: "0px",
    margin: "70px 0 0 0",
  },
  rightContent: {
    background: "#ffffff",
    textAlign: "center",
    backgroundRepeat: "no-repeat",
    opacity: "1",
    position: "relative",
    height: "1em",
    margin: " 60px 0 0 0",
  },
  keralaPoliceLogo: {
    width: "148px",
    padding: "0px",
    marginBottom: "-50px",
    margin: "70px 0 0 0",
  },

  h2: {
    letterSpacing: "0px",
    color: "#1daab1",
    textTransform: "uppercase",
    opacity: "1",
    fontSize: "24px",
    margin: "0",
    fontWeight: "normal",
    marginBottom: "30px",
  },
  form: {
    padding: "0px",
    margin: "30px 0 0 0",
  },
  TextField: {
    width: "100%",
    height: "50px",
    padding: "0px",
    paddingBottom: "55px",

    margin: " 0 0 15px 0",
    background: "#ffffff",
    backgroundRepeat: "no-repeat",
    borderColor: "#c4ccdc",
    borderRadius: "8px",
    color: " #98a1b2",
    opacity: "1",
  },
  // marginTOP: {
  //   marginTop: "35px",
  //   marginLeft: "-1px",
  //   margin: " 20px ",
  //   width: "100%",
  //   height: "54px",
  //   background: "#9bc5c7",
  //   borderRadius: "8px",
  //   backgroundRepeat: "no-repeat",
  //   letterSpacing: "0px",
  //   color: "#ffffff",
  //   opacity: "1",
  //   fontSize: "16px",
  //   textTransform: "none",
  // },
  forgotpassword: {
    letterSpacing: "0px",
    color: "#1daab1",
    opacity: "1",
    fontSize: "10px",
    textDecoration: "none",
  },
  // dontHaveAccount: {
  //   letterSpacing: "0px",
  //   color: "#98a1b2"
  // },
  //   powerdByText: {
  //     marginTop: "10px",
  //     letterSpacing: "0px",
  //     color: "#98a1b2",
  //     opacity: "1",
  //     fontSize: "14px",
  //   },
  ultsLogo: {
    padding: "0 0 0 10px",
    margin: "0px",
    width: "64px",
  },

  root: {
    flexGrow: 1,
    height: "100%",
    marginTop: "-70px",
  },

  dontHaveAccount: {
    letterSpacing: "0px",
    color: "#1daab1",
    opacity: "1",
    fontSize: "12px",
    textDecoration: "none",
    // marginLeft: "-150px",
  },
  marginTOP: {
    marginTop: "5px",

    margin: "0 0 20px 0",
    width: "100%",
    height: "49px",
    background: "#1daab1 ",
    backgroundRepeat: "no-repeat",
    borderRadius: "8px",
    opacity: "1",
    letterSpacing: "0px",
    color: "#ffffff",
    fontSize: "16px",
    textTransform: "none",
    "&:active": {
      backgroundColor: " #1daab1",
      color: "#ffffff",
    },
    "&:hover": {
      backgroundColor: " #1daab1",
      color: "#ffffff",
    },
  },
  a: {
    letterSpacing: "0px",
    color: "#1daab1 ",
    opacity: "1",
    fontSize: "14px",
    textDecoration: "none",
  },
  TextField: {
    width: "100%",
    height: "50px",
    padding: "0",
    paddingBottom: "5px",
    margin: "0 0 20px 0",
    background: "#ffffff 0% 0% ",
    backgroundRepeat: "no-repeat",
    borderColor: "#c4ccdc",
    borderRadius: "8px",
    color: "#98a1b2",
    opacity: "1",
  },
  form1: {
    padding: "0",
    margin: "30px 0 0 0",
  },
});

export default styles;
